import Link from 'next/link';
import { isAdmin, authConfigured } from '@/lib/auth';
import { listBeers } from '@/lib/db';
import { dateLabel } from '@/components/beer-label';
import { Submit } from '@/components/submit';
import { logout, stageImport } from './actions';
export const dynamic='force-dynamic';
export const metadata={title:'Braukeller',robots:{index:false,follow:false}};
export default async function Admin({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){const query=await searchParams;const loggedIn=await isAdmin();if(!loggedIn)return <section className="admin login section"><p className="eyebrow">NUR FÜR DEN BRAUMEISTER</p><h1>Dein Braukeller.</h1><p>Sude importieren, Etiketten gestalten und deine Biere veröffentlichen.</p>{query.error&&<p className="notice error" role="alert">Anmeldung fehlgeschlagen. Nur der freigeschaltete GitHub-Account hat Zugriff.</p>}{authConfigured()?<a className="button" href="/api/auth/login">Mit GitHub anmelden ↗</a>:<div className="notice">Die Admin-Anmeldung wird noch eingerichtet. Der Bereich ist bis dahin gesperrt.</div>}<Link className="text-link" href="/">Zurück zum Bier</Link></section>;
const beers=await listBeers(false);return <section className="admin section"><div className="admin-heading"><div><p className="eyebrow">KRAUSBRÄU VERWALTUNG</p><h1>Dein Braukeller.</h1></div><form action={logout}><button className="secondary">Abmelden</button></form></div>{query.success&&<p className="notice" role="status">{query.success==='deleted'?'Sud gelöscht. Er bleibt bei künftigen Imports zunächst abgewählt.':'Importauswahl übernommen. Eigene Texte und Veröffentlichungen wurden beibehalten.'}</p>}{query.error&&<p className="notice error" role="alert">{query.error==='sqlite'?'Die Datei konnte nicht gelesen werden. Bitte eine konsistente Kopie der Brauhelfer-Datenbank verwenden.':'Bitte eine gültige SQLite-Datei bis 3 MB auswählen. Importvorschauen laufen nach 24 Stunden ab.'}</p>}<form action={stageImport} className="panel"><h2>Neuer Stand aus dem Brauhelfer</h2><p>Die Datei wird zuerst geprüft. Im nächsten Schritt bestätigst du den Import. Neue Sude bleiben privat.</p><label htmlFor="database">SQLite-Datei (max. 3 MB)</label><input id="database" name="database" type="file" accept=".sqlite,.sqlite3,.db" required/><Submit pending="Wird geprüft …">Import prüfen</Submit></form><h2>Deine Sude <small>({beers.length})</small></h2><div className="admin-list">{beers.map(b=><Link href={`/admin/beer/${b.id}`} key={b.id} className="archive-row"><span className="archive-number">{b.brew.number}</span><div><h3>{b.display_name||b.brew.name}</h3><span>{dateLabel(b.brew.date)} · {b.published?'Veröffentlicht':'Privat'}</span></div><span>Bearbeiten ↗</span></Link>)}</div></section>}
