import Image from 'next/image';
import { BeerColor } from './beer-color';
import { Arrow } from './arrow';
import { MetricScale } from './metric-scale';
import Link from 'next/link';
import type { CSSProperties, ReactNode } from 'react';
import type { Beer } from '@/lib/types';
export const format=(n:number|null,digits=1)=>n===null?'—':new Intl.NumberFormat('de-DE',{maximumFractionDigits:digits}).format(n);
export function dateLabel(date:string|null) {return date?new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'UTC'}).format(new Date(date.slice(0,10)+'T12:00:00Z')):'Noch nicht gebraut';}
export function statusLabel(beer:Beer) { return beer.brew.bottledDate?'Abgefüllt':beer.brew.date?'In Gärung':'Rezeptentwurf'; }
export function BeerLabel({beer,preview=false,navigation}:{beer:Beer;preview?:boolean;navigation?:ReactNode}) { const b=beer.brew; const name=beer.display_name||b.name; const hops=[...new Set(b.hops.map(h=>h.name))]; const accent=/^#[0-9a-f]{6}$/i.test(beer.accent)?beer.accent:'#e9b44c';
 return <article className="label-page" style={{'--accent':accent} as CSSProperties}>
 <style>{`:root { --accent: ${accent}; }`}</style>
 {preview&&<div className="notice">Private Vorschau · <Link href={`/admin/beer/${beer.id}`}>Zurück zur Bearbeitung</Link></div>}
 <section className="hero"><div className="hero-copy"><div className="eyebrow">HANDGEBRAUT · SUD {String(beer.public_number??b.number).padStart(2,'0')}</div><p className="style-name">{b.style||'Hausgebraut'}</p><h1>{name}</h1><p className="hero-description">{beer.description||'Ein selbst gebrautes Bier von KrausBräu. Kleine Menge, eigener Charakter.'}</p><div className="hero-foot"><span className="pill">{statusLabel(beer)}</span><span>Gebraut am {dateLabel(b.date)}</span></div><a className="text-link" href="#bier">Das steckt drin <Arrow down/></a></div>
 <div className="hero-art">{beer.image_url?<Image src={beer.image_url} alt={`Illustration zum Bier ${name}`} fill sizes="(max-width: 760px) 100vw, 50vw" priority unoptimized={beer.image_url.startsWith('https:')} />:<div className="type-art" aria-label={`Sud ${b.number}`}>#{b.number}</div>}<div className="art-stamp"><span>KRAUSBRÄU</span><b>#{String(beer.public_number??b.number).padStart(2,'0')}</b><span>KLEINER SUD. EIGENER CHARAKTER.</span></div></div></section>
 <section id="bier" className="stats" aria-label="Bierdaten"><div><span>Alkohol</span><strong>{b.abv===null?'Noch offen':`${format(b.abv)} %`}</strong><small>{b.abv===null?'Nach der Gärung':'vol. · berechnet'}</small><MetricScale label="Alkohol" value={b.abv} max={12} unit="% vol."/></div><div><span>Stammwürze</span><strong>{format(b.originalGravity)} <em>°P</em></strong><small>Beim Anstellen</small><MetricScale label="Stammwürze" value={b.originalGravity} max={25} unit="°P"/></div><div><span>Bittere</span><strong>{format(b.ibu,0)} <em>IBU</em></strong><small>Laut Rezept</small><MetricScale label="Bittere" value={b.ibu} max={100} unit="IBU"/></div><div className="color-stat"><span>Bierfarbe</span><div className="color-stat-value"><strong>{format(b.ebc,0)} <em>EBC</em></strong><BeerColor ebc={b.ebc}/></div><small>Berechnet · Farbton angenähert</small><MetricScale label="Bierfarbe" value={b.ebc} max={120} unit="EBC"/></div></section>
 {navigation}
 <section className="ingredients section"><div className="section-intro"><span className="eyebrow">DER CHARAKTER BEGINNT HIER</span><h2>Malz. Hopfen.<br/>Hefe. Handwerk.</h2><p>Die Zutaten für diesen Sud. Im Kleinen gebraut, bis ins Detail festgehalten.</p></div><div className="ingredient-list"><div className="ingredient"><span className="ingredient-number">01</span><div><h3>Die Malzbasis</h3>{b.malts.map((m,i)=><div className="malt" key={i}><div><span>{m.name}</span><strong>{format(m.share??0)} %</strong></div><div className="bar"><span style={{width:`${Math.max(0,Math.min(100,m.share??0))}%`}}/></div></div>)}</div></div><div className="ingredient"><span className="ingredient-number">02</span><div><h3>Der Hopfen</h3><p>{hops.join(' · ')||'Keine Angabe'}</p></div></div><div className="ingredient"><span className="ingredient-number">03</span><div><h3>Die Hefe</h3><p>{b.yeast.join(' · ')||'Keine Angabe'}</p></div></div></div></section>
 {beer.tasting_notes&&<section className="tasting section"><span className="eyebrow">PERSÖNLICH VERKOSTET</span><h2>So schmeckt’s.</h2><p>{beer.tasting_notes}</p></section>}
 <section className="details-section"><details><summary>Für Braunerds <span>Rezept & Suddetails +</span></summary><div className="recipe"><dl><div><dt>Geplante Ausschlagmenge</dt><dd>{format(b.volume)} l</dd></div><div><dt>Zielstammwürze</dt><dd>{format(b.plannedGravity)} °P</dd></div><div><dt>Braudatum</dt><dd>{dateLabel(b.date)}</dd></div>{b.bottledDate&&<div><dt>Abgefüllt am</dt><dd>{dateLabel(b.bottledDate)}</dd></div>}</dl><h3>Schüttung</h3>{b.malts.map((m,i)=><p key={i}>{m.name} <b>{new Intl.NumberFormat('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(m.amount)} kg</b></p>)}{b.fermentation.length>0&&<><h3>Gärprotokoll</h3><div className="table-scroll"><table><thead><tr><th>Datum</th><th>Restextrakt</th><th>Temperatur</th></tr></thead><tbody>{b.fermentation.map((f,i)=><tr key={i}><td>{dateLabel(f.date)}</td><td>{format(f.extract)} °P</td><td>{format(f.temperature)} °C</td></tr>)}</tbody></table></div></>}{b.sourceId===37&&<p className="source">Rezeptgrundlage: „Gurgelrutscher“ von horstibus, Maische, Malz und mehr (05.02.2013). Braudaten dieses Suds: KrausBräu.</p>}</div></details></section>
 </article>;
}
